### ISSUE TITLE
Unable to build application(obd-parser) with ionic frmework

### ISSUE THREAD

**Issue by nitinsr013** [evanshortiss/obd-parser#5]
Hi 
 
I have created a new application in ionic and when I run command ionic serve then its build and ran fine.
Now I install the obd-parser and on home.ts I have added the below line at top.

import * as OBD from 'obd-parser';

After adding this line my application its stop working. Please refer the attached screen shot.
![iconic](https://user-images.githubusercontent.com/9943162/28866171-bfbc2f64-778f-11e7-8e17-689835e17fc3.jpg)

**Comment by evanshortiss** [comment]
@nitinsr013 that's an odd error, it looks like the comments are not being parsed correctly. Did you get it figured out?

I'm going to close this since it does not appear to be a bug with this library, and is most likely an issue with the Ionic/Angular build process. Please reopen if you have found otherwise.
